[package]
name = "pallet-revive-eth-rpc"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "An Ethereum JSON-RPC server for pallet-revive."
publish = false

[package.metadata.polkadot-sdk]
exclude-from-umbrella = true

[[bin]]
name = "eth-rpc"
path = "src/main.rs"

[[example]]
name = "deploy"
path = "examples/rust/deploy.rs"
required-features = ["example"]

[[example]]
name = "transfer"
path = "examples/rust/transfer.rs"
required-features = ["example"]

[[example]]
name = "rpc-playground"
path = "examples/rust/rpc-playground.rs"
required-features = ["example"]

[[example]]
name = "extrinsic"
path = "examples/rust/extrinsic.rs"
required-features = ["example"]

[[example]]
name = "remark-extrinsic"
path = "examples/rust/remark-extrinsic.rs"
required-features = ["example"]

[dependencies]
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
futures = { workspace = true, features = ["thread-pool"] }
jsonrpsee = { workspace = true, features = ["full"] }
<<<<<<< HEAD
serde_json = { workspace = true }
thiserror = { workspace = true }
sp-crypto-hashing.workspace = true
subxt = { workspace = true, default-features = true, features = [
	"unstable-reconnecting-rpc-client",
] }
tokio = { workspace = true, features = ["full"] }
codec = { workspace = true, features = ["derive"] }
log.workspace = true
pallet-revive.workspace = true
pallet-revive.default-features = true
sp-core.workspace = true
sp-core.default-features = true
sp-weights.workspace = true
sp-weights.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sc-rpc.workspace = true
sc-rpc.default-features = true
sc-rpc-api.workspace = true
sc-rpc-api.default-features = true
sc-cli.workspace = true
sc-cli.default-features = true
sc-service.workspace = true
sc-service.default-features = true
prometheus-endpoint.workspace = true
prometheus-endpoint.default-features = true

rlp = { workspace = true, optional = true }
subxt-signer = { workspace = true, optional = true, features = [
	"unstable-eth",
] }
hex = { workspace = true, optional = true }
hex-literal = { workspace = true, optional = true }
scale-info = { workspace = true }
secp256k1 = { workspace = true, optional = true, features = ["recovery"] }
env_logger = { workspace = true }

[features]
example = ["hex", "hex-literal", "rlp", "secp256k1", "subxt-signer"]
=======
log = { workspace = true }
pallet-revive = { workspace = true, default-features = true }
prometheus-endpoint = { workspace = true, default-features = true }
rlp = { workspace = true }
sc-cli = { workspace = true, default-features = true }
sc-rpc = { workspace = true, default-features = true }
sc-rpc-api = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
sp-arithmetic = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-crypto-hashing = { workspace = true }
sp-runtime = { workspace = true, default-features = true }
sp-weights = { workspace = true, default-features = true }
sqlx = { workspace = true, features = ["macros", "runtime-tokio", "sqlite"] }
subxt = { workspace = true, default-features = true, features = ["reconnecting-rpc-client"] }
subxt-signer = { workspace = true, features = ["unstable-eth"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[dev-dependencies]
hex-literal = { workspace = true }
pallet-revive-fixtures = { path = "../fixtures", default-features = false }
substrate-cli-test-utils = { path = "../../../test-utils/cli" }
subxt-signer = { workspace = true, features = ["unstable-eth"] }
<<<<<<< HEAD
=======

[build-dependencies]
git2 = { workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
