[package]
name = "pallet-revive-uapi"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Exposes all the host functions that a contract can import."
publish = false

[package.metadata.polkadot-sdk]
exclude-from-umbrella = true

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["unstable-hostfn"]
targets = ["riscv64imac-unknown-none-elf"]

[dependencies]
paste = { workspace = true }
bitflags = { workspace = true }
<<<<<<< HEAD
scale-info = { features = ["derive"], optional = true, workspace = true }
codec = { features = [
	"derive",
	"max-encoded-len",
], optional = true, workspace = true }
=======
codec = { features = ["derive", "max-encoded-len"], optional = true, workspace = true }
pallet-revive-proc-macro = { workspace = true }
scale-info = { features = ["derive"], optional = true, workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[target.'cfg(target_arch = "riscv32")'.dependencies]
polkavm-derive = { version = "0.14.0" }

<<<<<<< HEAD
[package.metadata.docs.rs]
default-target = ["wasm32-unknown-unknown"]

=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
[features]
default = ["scale"]
scale = ["dep:codec", "scale-info"]
