[package]
name = "coretime-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Coretime Rococo emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
<<<<<<< HEAD
coretime-rococo-runtime.default-features = true
coretime-rococo-runtime.workspace = true
cumulus-primitives-core.workspace = true
emulated-integration-tests-common.workspace = true
frame-support.workspace = true
parachains-common.default-features = true
parachains-common.workspace = true
sp-core.workspace = true
=======
# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }

# Cumulus
coretime-rococo-runtime = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }
