[package]
name = "pallet-nft-fractionalization"
version = "22.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME pallet to convert non-fungible to fungible tokens."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
<<<<<<< HEAD
=======
frame = { workspace = true, features = ["runtime"] }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
log = { workspace = true }
scale-info = { features = ["derive"], workspace = true }
<<<<<<< HEAD
frame-benchmarking = { optional = true, workspace = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-assets.workspace = true
pallet-nfts.workspace = true
sp-runtime.workspace = true

[dev-dependencies]
pallet-balances = { default-features = true, path = "../balances" }
sp-core = { default-features = true, path = "../../primitives/core" }
sp-io = { default-features = true, path = "../../primitives/io" }
sp-std = { default-features = true, path = "../../primitives/std" }
=======

[dev-dependencies]
pallet-balances = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"log/std",
	"pallet-assets/std",
	"pallet-nfts/std",
	"scale-info/std",
<<<<<<< HEAD
	"sp-runtime/std",
=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-nfts/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-nfts/try-runtime",
]
