[package]
name = "pallet-root-offences"
version = "36.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME root offences pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
scale-info = { features = ["derive"], workspace = true }
pallet-session = { features = ["historical"], workspace = true }
<<<<<<< HEAD
pallet-staking.workspace = true
frame-support.workspace = true
frame-system.workspace = true
sp-runtime.workspace = true
sp-staking.workspace = true
=======
pallet-staking = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-staking = { workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[dev-dependencies]
pallet-balances = { default-features = true, path = "../balances" }
pallet-timestamp = { default-features = true, path = "../timestamp" }
pallet-staking-reward-curve = { default-features = true, path = "../staking/reward-curve" }

<<<<<<< HEAD
sp-core = { default-features = true, path = "../../primitives/core" }
sp-io = { path = "../../primitives/io", default-features = false }
sp-std = { default-features = true, path = "../../primitives/std" }
=======
sp-io = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

frame-election-provider-support = { default-features = true, path = "../election-provider-support" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-staking/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"sp-runtime/try-runtime",
]
<<<<<<< HEAD
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
]
=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
