[package]
name = "pallet-xcm-benchmarks"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "20.0.0"
description = "Benchmarks for the XCM pallet"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
<<<<<<< HEAD
frame-benchmarking.workspace = true
frame-support.workspace = true
frame-system.workspace = true
=======
frame-benchmarking = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
scale-info = { features = ["derive"], workspace = true }
sp-io.workspace = true
sp-runtime.workspace = true
xcm-builder.workspace = true
xcm-executor.workspace = true
xcm.workspace = true

[dev-dependencies]
<<<<<<< HEAD
pallet-assets = { default-features = true, workspace = true }
pallet-balances = { default-features = true, workspace = true }
sp-tracing = { default-features = true, workspace = true }
xcm = { default-features = true, workspace = true }
=======
pallet-balances = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }
xcm = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"xcm-builder/std",
	"xcm-executor/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
