[package]
name = "polkadot-node-metrics"
description = "Subsystem metric helpers"
version = "22.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }

bs58 = { features = ["alloc"], workspace = true, default-features = true }
codec = { workspace = true, default-features = true }
<<<<<<< HEAD
polkadot-primitives.default-features = true
polkadot-primitives.workspace = true
prometheus-endpoint.default-features = true
prometheus-endpoint.workspace = true
sc-cli.default-features = false
sc-cli.workspace = true
sc-service.default-features = false
sc-service.workspace = true
sc-tracing.default-features = true
sc-tracing.workspace = true
=======
metered = { features = ["futures_channel"], workspace = true }
polkadot-primitives = { workspace = true, default-features = true }
prometheus-endpoint = { workspace = true, default-features = true }
# Both `sc-service` and `sc-cli` are required by runtime metrics `logger_hook()`.
sc-cli = { workspace = true, default-features = false }
sc-service = { workspace = true, default-features = false }
sc-tracing = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[dev-dependencies]
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { features = ["client-legacy", "tokio"], workspace = true }
polkadot-test-service = { features = ["runtime-metrics"], workspace = true }
prometheus-parse = { workspace = true }
<<<<<<< HEAD
sc-service = { default-features = true, workspace = true }
sp-keyring = { default-features = true, workspace = true }
=======
sc-service = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
tokio = { workspace = true, default-features = true }

[features]
default = []
runtime-metrics = []
runtime-benchmarks = [
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-test-service/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
]
