[package]
name = "chain-spec-guide-runtime"
description = "A minimal runtime for chain spec guide"
version = "0.1.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
codec = { workspace = true }
docify = { workspace = true }
frame = { features = ["experimental", "runtime"], workspace = true }
frame-support.workspace = true
pallet-balances.workspace = true
pallet-sudo.workspace = true
pallet-timestamp.workspace = true
pallet-transaction-payment-rpc-runtime-api.workspace = true
pallet-transaction-payment.workspace = true
scale-info = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
<<<<<<< HEAD
=======

# this is a frame-based runtime, thus importing `frame` with runtime feature enabled.
frame = { features = ["experimental", "runtime"], workspace = true }

# genesis builder that allows us to interact with runtime genesis config
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
sp-application-crypto = { features = ["serde"], workspace = true }
sp-core.workspace = true
sp-genesis-builder.workspace = true
sp-keyring.workspace = true
sp-runtime = { features = ["serde"], workspace = true }

[dev-dependencies]
<<<<<<< HEAD
chain-spec-builder = { default-features = true, workspace = true }
=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
cmd_lib = { workspace = true }
sc-chain-spec = { default-features = true, workspace = true }

[build-dependencies]
substrate-wasm-builder = { optional = true, workspace = true, default-features = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",

	"frame-support/std",
	"frame/std",

	"sp-application-crypto/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-keyring/std",
	"sp-runtime/std",

	"serde/std",
	"serde_json/std",
	"substrate-wasm-builder",
]
