[package]
name = "parachains-relay"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-std = { workspace = true }
async-trait = { workspace = true }
bp-polkadot-core.default-features = true
bp-polkadot-core.workspace = true
futures = { workspace = true }
log = { workspace = true }
<<<<<<< HEAD
relay-substrate-client.workspace = true
relay-utils.workspace = true
=======
relay-utils = { workspace = true }

# Bridge dependencies
bp-polkadot-core = { workspace = true, default-features = true }
relay-substrate-client = { workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[dev-dependencies]
relay-substrate-client = { features = ["test-helpers"], workspace = true }
sp-core = { default-features = true, workspace = true }
