[package]
name = "substrate-frame-rpc-support"
version = "44.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Substrate RPC for FRAME's support"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
frame-support.default-features = true
frame-support.workspace = true
jsonrpsee = { features = ["jsonrpsee-types"], workspace = true }
<<<<<<< HEAD
sc-rpc-api.default-features = true
sc-rpc-api.workspace = true
=======
sc-rpc-api = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
scale-info = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
sp-storage.default-features = true
sp-storage.workspace = true

[dev-dependencies]
frame-system = { default-features = true, workspace = true }
jsonrpsee = { features = ["jsonrpsee-types", "ws-client"], workspace = true }
<<<<<<< HEAD
sp-core = { default-features = true, workspace = true }
sp-runtime = { default-features = true, workspace = true }
=======
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
tokio = { workspace = true, default-features = true }
