[package]
name = "polkadot-voter-bags"
version = "22.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI to generate voter bags for Polkadot runtimes"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
clap = { features = ["derive"], workspace = true }
<<<<<<< HEAD
generate-bags.default-features = true
generate-bags.workspace = true
westend-runtime.workspace = true
=======

generate-bags = { workspace = true, default-features = true }

westend-runtime = { workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
