[package]
name = "frame-omni-bencher"
version = "0.10.0"
description = "Freestanding benchmark runner for any Polkadot runtime."
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
clap = { features = ["derive"], workspace = true }
<<<<<<< HEAD
cumulus-primitives-proof-size-hostfunction.workspace = true
cumulus-primitives-proof-size-hostfunction.default-features = true
frame-benchmarking-cli.workspace = true
sc-cli.workspace = true
sc-cli.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-statement-store.workspace = true
sp-statement-store.default-features = true
=======
cumulus-primitives-proof-size-hostfunction = { workspace = true, default-features = true }
frame-benchmarking-cli = { workspace = true }
sc-cli = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-statement-store = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
tracing-subscriber = { workspace = true }
log = { workspace = true }

[dev-dependencies]
<<<<<<< HEAD
=======
assert_cmd = { workspace = true }
cumulus-test-runtime = { workspace = true }
sc-chain-spec = { workspace = true }
sp-genesis-builder = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
tempfile = { workspace = true }
assert_cmd = { workspace = true }
cumulus-test-runtime = { path = "../../../../cumulus/test/runtime" }
sp-tracing = { default-features = true, path = "../../../primitives/tracing" }
sp-genesis-builder = { default-features = true, path = "../../../primitives/genesis-builder" }
sc-chain-spec = { path = "../../../client/chain-spec", default-features = false }
