[package]
name = "pallet-contracts-uapi"
version = "14.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Exposes all the host functions that a contract can import."

[lints]
workspace = true

<<<<<<< HEAD
[dependencies]
bitflags = { workspace = true }
codec = { features = ["derive", "max-encoded-len"], optional = true, workspace = true }
paste = { workspace = true }
scale-info = { features = ["derive"], optional = true, workspace = true }

=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]

[dependencies]
bitflags = { workspace = true }
codec = { features = ["derive", "max-encoded-len"], optional = true, workspace = true }
paste = { workspace = true }
scale-info = { features = ["derive"], optional = true, workspace = true }

[features]
default = ["scale"]
scale = ["dep:codec", "scale-info"]
