[package]
name = "polkadot-node-core-provisioner"
version = "21.0.0"
description = "Responsible for assembling a relay chain block from a set of available parachain candidates"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bitvec = { features = ["alloc"], workspace = true }
futures = { workspace = true }
<<<<<<< HEAD
gum.workspace = true
gum.default-features = true
=======
futures-timer = { workspace = true }
gum = { workspace = true, default-features = true }
polkadot-node-primitives = { workspace = true, default-features = true }
polkadot-node-subsystem = { workspace = true, default-features = true }
polkadot-node-subsystem-util = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
thiserror = { workspace = true }
polkadot-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem-util.default-features = true
futures-timer = { workspace = true }
fatality = { workspace = true }
schnellru = { workspace = true }

[dev-dependencies]
<<<<<<< HEAD
sp-application-crypto = { default-features = true, path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { default-features = true, path = "../../../../substrate/primitives/keystore" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
polkadot-primitives = { features = ["test"], path = "../../../primitives", default-features = false }

rstest = { workspace = true }
=======
polkadot-node-subsystem-test-helpers = { workspace = true }
polkadot-primitives = { workspace = true, features = ["test"] }
polkadot-primitives-test-helpers = { workspace = true }
sp-application-crypto = { workspace = true, default-features = true }
sp-keystore = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
