[package]
name = "bridge-hub-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Rococo emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
<<<<<<< HEAD
bp-messages.workspace = true
bridge-hub-common.workspace = true
bridge-hub-rococo-runtime.default-features = true
bridge-hub-rococo-runtime.workspace = true
emulated-integration-tests-common.workspace = true
frame-support.workspace = true
parachains-common.default-features = true
parachains-common.workspace = true
sp-core.workspace = true
sp-keyring.workspace = true
=======
# Substrate
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }

# Polkadot Dependencies
xcm = { workspace = true }

# Bridge dependencies
bp-messages = { workspace = true }

# Cumulus
bridge-hub-common = { workspace = true }
bridge-hub-rococo-runtime = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
testnet-parachains-constants = { features = ["rococo"], workspace = true, default-features = true }
xcm.workspace = true
