[package]
name = "pallet-tx-pause"
version = "20.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME transaction pause pallet"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
docify = { workspace = true }
<<<<<<< HEAD
frame-benchmarking = { optional = true, workspace = true }
frame-support.workspace = true
frame-system.workspace = true
scale-info = { features = ["derive"], workspace = true }
sp-runtime.workspace = true
pallet-balances = { optional = true, workspace = true }
pallet-utility = { optional = true, workspace = true }
pallet-proxy = { optional = true, workspace = true }

[dev-dependencies]
sp-core = { default-features = true, path = "../../primitives/core" }
sp-io = { default-features = true, path = "../../primitives/io" }
pallet-balances = { default-features = true, path = "../balances" }
pallet-utility = { default-features = true, path = "../utility" }
pallet-proxy = { default-features = true, path = "../proxy" }
=======
frame = { workspace = true, features = ["runtime"] }
scale-info = { features = ["derive"], workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true, default-features = true }
pallet-proxy = { workspace = true, default-features = true }
pallet-utility = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
	"scale-info/std",
<<<<<<< HEAD
	"sp-runtime/std",
=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-utility/try-runtime",
]
