[package]
name = "pallet-tx-pause"
version = "21.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "FRAME transaction pause pallet"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = ["derive"], workspace = true }
docify = { workspace = true }
frame = { workspace = true, features = ["runtime"] }
<<<<<<< HEAD
pallet-balances = { optional = true, workspace = true }
pallet-proxy = { optional = true, workspace = true }
pallet-utility = { optional = true, workspace = true }
scale-info = { features = ["derive"], workspace = true }

[dev-dependencies]
pallet-balances = { default-features = true, workspace = true }
pallet-proxy = { default-features = true, workspace = true }
pallet-utility = { default-features = true, workspace = true }
=======
scale-info = { features = ["derive"], workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true, default-features = true }
pallet-proxy = { workspace = true, default-features = true }
pallet-utility = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[features]
default = ["std"]
std = [
	"codec/std",
	"frame/std",
<<<<<<< HEAD
	"pallet-balances?/std",
	"pallet-proxy?/std",
	"pallet-utility?/std",
=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
	"scale-info/std",
]
runtime-benchmarks = [
	"frame/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
]
try-runtime = [
	"frame/try-runtime",
<<<<<<< HEAD
	"pallet-balances?/try-runtime",
	"pallet-proxy?/try-runtime",
	"pallet-utility?/try-runtime",
=======
	"pallet-balances/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-utility/try-runtime",
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
]
