[package]
name = "pallet-bags-list-fuzzer"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzzer for FRAME pallet bags list"
publish = false

[lints]
workspace = true

[[bin]]
name = "bags-list"
path = "src/main.rs"

[dependencies]
frame-election-provider-support = { features = ["fuzz"], workspace = true, default-features = true }
honggfuzz = { workspace = true }
pallet-bags-list = { features = ["fuzz"], workspace = true, default-features = true }
<<<<<<< HEAD

[[bin]]
name = "bags-list"
path = "src/main.rs"
=======
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
