[package]
name = "frame-election-solution-type-fuzzer"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzzer for phragmén solution type implementation."
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "compact"
path = "src/compact.rs"

[dependencies]
honggfuzz = { workspace = true }

codec = { features = ["derive"], workspace = true }
<<<<<<< HEAD
scale-info = { features = ["derive"], workspace = true }
frame-election-provider-solution-type.workspace = true
frame-election-provider-solution-type.default-features = true
frame-election-provider-support.workspace = true
frame-election-provider-support.default-features = true
sp-arithmetic.workspace = true
sp-arithmetic.default-features = true
sp-runtime.workspace = true
sp-runtime.default-features = true
sp-npos-elections.workspace = true
frame-support.workspace = true
frame-support.default-features = true

[[bin]]
name = "compact"
path = "src/compact.rs"
=======
frame-election-provider-solution-type = { workspace = true, default-features = true }
frame-election-provider-support = { workspace = true, default-features = true }
sp-arithmetic = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
# used by generate_solution_type:
frame-support = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
