[package]
name = "polkadot-node-core-backing"
version = "22.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "The Candidate Backing Subsystem. Tracks parachain candidates that can be backed, as well as the issuance of statements about candidates."
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bitvec = { features = ["alloc"], workspace = true }
fatality = { workspace = true }
futures = { workspace = true }
gum.default-features = true
gum.workspace = true
polkadot-erasure-coding.default-features = true
polkadot-erasure-coding.workspace = true
polkadot-node-primitives.default-features = true
polkadot-node-primitives.workspace = true
polkadot-node-subsystem-util.default-features = true
polkadot-node-subsystem-util.workspace = true
polkadot-node-subsystem.default-features = true
polkadot-node-subsystem.workspace = true
polkadot-parachain-primitives.default-features = true
polkadot-parachain-primitives.workspace = true
polkadot-primitives.default-features = true
polkadot-primitives.workspace = true
polkadot-statement-table.default-features = true
polkadot-statement-table.workspace = true
schnellru = { workspace = true }
sp-keystore.default-features = true
sp-keystore.workspace = true
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
futures = { features = ["thread-pool"], workspace = true }
polkadot-node-subsystem-test-helpers = { workspace = true }
polkadot-primitives = { features = ["test"], workspace = true, default-features = false }
polkadot-primitives-test-helpers = { workspace = true }
<<<<<<< HEAD
sc-keystore = { default-features = true, workspace = true }
sp-application-crypto = { default-features = true, workspace = true }
sp-core = { default-features = true, workspace = true }
sp-keyring = { default-features = true, workspace = true }
sp-tracing = { default-features = true, workspace = true }
=======
sc-keystore = { workspace = true, default-features = true }
sp-application-crypto = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))
