[package]
name = "cumulus-primitives-aura"
version = "0.17.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Core primitives for Aura in Cumulus"
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
<<<<<<< HEAD
sp-api.workspace = true
sp-consensus-aura.workspace = true
=======
# Substrate
sp-api = { workspace = true }
sp-consensus-aura = { workspace = true }
>>>>>>> 07827930 (Use original pr name in prdoc check (#60))

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-consensus-aura/std",
]
