name: Release branch check
on:
  push:
    branches:
      - release-v[0-9]+.[0-9]+.[0-9]+

  workflow_dispatch:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Run check
        shell: bash
        run: ./github/common/check-rel-br
