name: Clobber Stable

on:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  clobber-stable:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
        STABLE: stable
        UNSTABLE: master
        AUDITED: audited
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    
    - name: Prechecks
      run: |
        # Properly fetch tags
        git fetch --prune --unshallow origin tag $AUDITED
        git fetch origin $STABLE
        git checkout -q tags/$AUDITED || (echo "Could not find the '$AUDITED' tag." && exit 1)
        
        COMMIT=$(git rev-parse tags/$AUDITED)
        #$(git branch --contains $COMMIT | grep -q $UNSTABLE) || (echo "The '$AUDITED' tag is not on the '$UNSTABLE' branch." && exit 1)

        git config --global user.email "admin@parity.io"
        git config --global user.name "Parity Release Team"

    - name: Backup stable branch
      run: |
        # We will force push - better make a backup first.
        git archive -o /tmp/backup.tar.gz tags/$STABLE || true

    - name: Overwrite stable branch
      run: |
        git checkout --quiet origin/$STABLE

        # Delete all tracked files in the working directory
        git ls-files -z | xargs -0 rm -f

        # Find and delete any empty directories
        find . -type d -empty -delete

        git add . 1>/dev/null 2>/dev/null
        git commit -qm "Delete all files"

        # Grab the files from the commit
        git checkout --quiet tags/$AUDITED -- .

        # Stage, commit, and push the working directory which now matches 'audited' 1:1
        git status
        COMMIT=$(git rev-parse --short=10 tags/$AUDITED)
        git add . 1>/dev/null 2>/dev/null
        git commit --allow-empty --amend -qm "Clobber with $AUDITED ($COMMIT)"
        
    - name: Force push stable branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git log -3
        git push --verbose --force origin HEAD:$STABLE
